ALTER TABLE pasien ADD COLUMN no_hp VARCHAR(20) DEFAULT NULL;
ALTER TABLE pasien ADD COLUMN alamat VARCHAR(255) DEFAULT NULL;
ALTER TABLE pasien ADD COLUMN bpjs VARCHAR(50) DEFAULT NULL;
ALTER TABLE users 
ADD reset_token VARCHAR(255) NULL AFTER password_hash,
ADD reset_expired DATETIME NULL AFTER reset_token;
